service: tag-alexa-fifi

custom:
  stage: ${opt:stage, 'staging'}
  region: "sa-east-1"
  serverless-offline:
    port: 3000
  staging:
    appId: "amzn1.ask.skill.XXXXXX"
  production:
    appId: "amzn1.ask.skill.XXXXXX"

provider:
  name: aws
  runtime: nodejs14.x
  region: "sa-east-1"
  deploymentBucket:
    name: serverless.tag.deployment
  environment:
    STAGE: ${self:custom.stage}
    
functions:
  alexaHandler:
    handler: src/handler.handler
    events:
      - alexaSkill:
          appId:  ${self:custom.${self:custom.stage}.appId}


plugins:
  - serverless-plugin-typescript
  - serverless-offline